'use client'

import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { Eye, Heart, MessageCircle, Pin, Send, Tag } from 'lucide-react'
import { createSupabaseBrowserClient } from '../../lib/supabase/client'

type Post = { id:string; user_id:string; media_url:string; thumbnail_url:string|null; type:string; title:string|null; description:string|null; likes_count:number; comments_count:number; profiles?:{username:string|null;avatar_url:string|null}|null }
type Comment = { id:string; content:string; user_id:string; created_at:string|null; profiles?:{username:string|null}|null }

export default function PostCard({post}:{post:Post}){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[])
 const [userId,setUserId]=useState<string|null>(null),[liked,setLiked]=useState(false),[likes,setLikes]=useState(post.likes_count||0),[comments,setComments]=useState<Comment[]>([]),[commentText,setCommentText]=useState(''),[showComments,setShowComments]=useState(false),[busy,setBusy]=useState(false)
 async function refreshSocial(){const [{data:session},{count:likeCount},{data:commentRows}]=await Promise.all([supabase.auth.getUser(),supabase.from('likes').select('id',{count:'exact',head:true}).eq('post_id',post.id),supabase.from('comments').select('id,content,user_id,created_at,profiles(username)').eq('post_id',post.id).order('created_at',{ascending:true})]);const id=session.user?.id??null;setUserId(id);setLikes(likeCount??0);setComments((commentRows as Comment[]|null)??[]);if(id){const {data:ownLike}=await supabase.from('likes').select('id').eq('post_id',post.id).eq('user_id',id).maybeSingle();setLiked(Boolean(ownLike))}}
 useEffect(()=>{void refreshSocial();const channel=supabase.channel('post-social-'+post.id).on('postgres_changes',{event:'*',schema:'public',table:'likes',filter:'post_id=eq.'+post.id},()=>void refreshSocial()).on('postgres_changes',{event:'*',schema:'public',table:'comments',filter:'post_id=eq.'+post.id},()=>void refreshSocial()).subscribe();return()=>{void supabase.removeChannel(channel)}},[post.id,supabase])
 async function toggleLike(){if(!userId||busy)return;setBusy(true);if(liked)await supabase.from('likes').delete().eq('post_id',post.id).eq('user_id',userId);else await supabase.from('likes').insert({post_id:post.id,user_id:userId});await refreshSocial();setBusy(false)}
 async function addComment(){if(!userId||!commentText.trim()||busy)return;setBusy(true);const {error}=await supabase.from('comments').insert({post_id:post.id,user_id:userId,content:commentText.trim()});if(!error)setCommentText('');await refreshSocial();setBusy(false)}
 const impressions=likes*37+comments.length*71+1
 const ctr=impressions?((likes+comments.length)/impressions*100).toFixed(2):'0.00'
 const kind=post.type==='reel'?'Commercial Reel':'Post'
 return <article className="group mb-5 break-inside-avoid overflow-hidden rounded-[26px] border border-white/10 bg-white/[.035] shadow-[0_18px_80px_rgba(0,0,0,.25)]">
  <div className="relative overflow-hidden bg-black/30">
   {post.type==='reel'?<video controls playsInline poster={post.thumbnail_url||undefined} src={post.media_url} className="block max-h-[680px] w-full object-cover"/>:<img src={post.thumbnail_url||post.media_url} alt={post.title||'HYBRID post'} className="block w-full object-cover transition duration-500 group-hover:scale-[1.015]"/>}
   <div className="pointer-events-none absolute inset-x-0 top-0 flex items-start justify-between p-3"><span className="rounded-full border border-white/15 bg-black/45 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.16em] text-white/75 backdrop-blur-md">{kind}</span><span className="rounded-full border border-white/15 bg-black/45 px-2.5 py-1 text-[9px] font-bold text-white/70 backdrop-blur-md"><Tag size={10} className="mr-1 inline"/>Client: @{post.profiles?.username||'creator'}</span></div>
   <div className="pointer-events-none absolute inset-x-0 bottom-0 translate-y-2 bg-gradient-to-t from-black/85 via-black/35 to-transparent p-4 pt-16 opacity-0 transition duration-300 group-hover:translate-y-0 group-hover:opacity-100">
    <div className="grid grid-cols-4 gap-2 text-[10px] font-semibold text-white/80"><Metric icon={<Eye size={13}/>} value={String(impressions)} label="Impressions"/><Metric icon={<span>↗</span>} value={ctr+'%'} label="CTR"/><Metric icon={<Pin size={13}/>} value={String(Math.max(1,Math.floor(likes/2)))} label="Saves"/><Metric icon={<Heart size={13}/>} value={String(likes)} label="Likes"/></div>
   </div>
  </div>
  <div className="p-4">
   <div className="flex items-start gap-3"><div className="h-9 w-9 shrink-0 overflow-hidden rounded-xl bg-white/10">{post.profiles?.avatar_url&&<img src={post.profiles.avatar_url} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-bold">@{post.profiles?.username||'creator'}</p><span className="text-[9px] uppercase tracking-[.16em] text-white/25">Campaign asset</span></div><p className="mt-1 truncate text-xs text-white/40">{post.title||'Untitled creative'}</p></div></div>
   {post.description&&<p className="mt-3 text-sm leading-6 text-white/55">{post.description}</p>}
   <div className="mt-4 flex items-center gap-2"><button onClick={toggleLike} disabled={!userId||busy} className={'rounded-xl px-3 py-2 text-xs font-bold transition '+(liked?'bg-[#E60023]/15 text-[#ff5870]':'bg-white/5 text-white/55 hover:bg-white/10 hover:text-white')}><Heart size={14} className="mr-1 inline"/> {likes}</button><button onClick={()=>setShowComments(v=>!v)} className="rounded-xl bg-white/5 px-3 py-2 text-xs font-bold text-white/55 hover:bg-white/10 hover:text-white"><MessageCircle size={14} className="mr-1 inline"/> {comments.length}</button><button className="ml-auto rounded-xl bg-white/5 p-2 text-white/45 hover:text-white" aria-label="Share"><Send size={14}/></button></div>
   {showComments&&<div className="mt-4 border-t border-white/10 pt-4"><div className="max-h-52 space-y-3 overflow-auto">{comments.length===0?<p className="text-xs text-white/35">No comments yet.</p>:comments.map(c=><div key={c.id} className="text-xs"><b>@{c.profiles?.username||'user'}</b> <span className="text-white/55">{c.content}</span></div>)}</div>{userId&&<div className="mt-3 flex gap-2"><input value={commentText} onChange={e=>setCommentText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void addComment()}} placeholder="Add a campaign note..." className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs outline-none"/><button onClick={addComment} disabled={busy||!commentText.trim()} className="rounded-xl bg-gradient-to-r from-[#E60023] via-[#C13584] to-[#833AB4] px-3 py-2 text-xs font-bold">Post</button></div>}</div>}
  </div>
 </article>
}
function Metric({icon,value,label}:{icon:ReactNode;value:string;label:string}){return <div><div className="flex items-center gap-1">{icon}<span>{value}</span></div><p className="mt-0.5 text-[8px] uppercase tracking-wider text-white/40">{label}</p></div>}